skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
face_auth = "42X4XP4LuW5jm2cCkZhib61iJx62dnw8AEEYJQzPhhJW"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
